name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo $GITHUB_TOKEN | docker login https://docker.pkg.github.com -u Orzelius --password-stdin
    - name: Tag docker image
      run: docker tag 09e243ec5029 docker.pkg.github.com/orzelius/docker-game/kaspar-game:$GITHUB_SHA
    - name: Build Image
      run: docker build .
    - name: push image
      run: docker push docker.pkg.github.com/orzelius/docker-game/kaspar-game:$GITHUB_SHA
